# Quantitative Momentum Strategy

In [1]:
import numpy as np
import pandas as pd
import math
import datetime
from scipy import stats
from pandas_datareader import data as pdr
import yfinance as yf
yf.pdr_override()

In [2]:
tickets = pd.read_csv('./data/BOVA11_holdings.csv')
tickets = tickets['Código']
tickets

0      VALE3
1      ITUB4
2      PETR4
3      BBDC4
4      B3SA3
       ...
76     HGTX3
77     ECOR3
78    CVCB11
79      XBZ0
80
Name: Código, Length: 81, dtype: object

In [3]:
columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']
stocks = pd.DataFrame(columns = columns)
today = datetime.datetime.today().strftime('%Y-%m-%d')
last_year = datetime.datetime.now() - datetime.timedelta(days=365)
last_year = last_year.strftime('%Y-%m-%d')

for ticket in tickets:
    try:
        data = pdr.get_data_yahoo(ticket+'.SA', start=last_year, end=today)
        close = list(data['Close'])
        size = len(close)
        one_year_return = (close[size-1]-close[0])/close[0]
        price = close[size-1]

        stocks = stocks.append(pd.Series([ticket, 
                                        price,
                                        one_year_return,
                                        'N/A'], 
                                        index = columns), 
                                ignore_index = True)
    except:
        pass

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- BRL.SA: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- CVCB11.SA: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- XBZ0.SA: No data found, symbol may be delisted
[*********************100%***********************]  1 of 1 completed

1 Failed download:
- .SA: No data found, symbol may be delisted

In [4]:
stocks

   Ticker      Price  One-Year Price Return Number of Shares to Buy
0   VALE3  82.269997               0.599339                     N/A
1   ITUB4  30.250000              -0.172367                     N/A
2   PETR4  27.410000              -0.092685                     N/A
3   BBDC4  25.629999              -0.259249                     N/A
4   B3SA3  58.529999               0.228332                     N/A
..    ...        ...                    ...                     ...
72  IGTA3  38.389999              -0.223032                     N/A
73  CVCB3  20.240000              -0.508738                     N/A
74  BEEF3   9.810000              -0.345791                     N/A
75  HGTX3  18.260000              -0.455251                     N/A
76  ECOR3  13.180000              -0.069209                     N/A

[77 rows x 4 columns]

In [5]:
stocks.sort_values('One-Year Price Return', ascending = False, inplace = True)
stocks = stocks[:25]
stocks.reset_index(drop = True, inplace = True)
stocks

    Ticker      Price  One-Year Price Return Number of Shares to Buy
0    WEGE3  71.970001               1.255406                     N/A
1    PRIO3  56.500000               1.107423                     N/A
2    MGLU3  23.719999               1.069357                     N/A
3    CSNA3  25.660000               0.949848                     N/A
4    VVAR3  17.730000               0.733138                     N/A
5    BRAP4  61.209999               0.703116                     N/A
6    USIM5  13.970000               0.605747                     N/A
7    VALE3  82.269997               0.599339                     N/A
8    RENT3  66.800003               0.553832                     N/A
9    SUZB3  52.680000               0.394389                     N/A
10   HAPV3  15.210000               0.362903                     N/A
11   GOAU4  10.630000               0.345570                     N/A
12   NTCO3  49.400002               0.343852                     N/A
13   GGBR4  23.049999               0.341676                     N/A
14  KLBN11  24.180000               0.337389                     N/A
15   MRFG3  14.180000               0.304508                     N/A
16   GNDI3  74.389999               0.266428                     N/A
17   BTOW3  76.199997               0.254734                     N/A
18   B3SA3  58.529999               0.228332                     N/A
19   RADL3  24.700001               0.201479                     N/A
20   CSAN3  75.570000               0.147434                     N/A
21  TAEE11  32.759998               0.118852                     N/A
22  BPAC11  82.080002               0.069586                     N/A
23   MRVE3  20.030001               0.029291                     N/A
24   UGPA3  21.950001               0.026661                     N/A

In [6]:
portfolio_size = 1e8
position_size = portfolio_size/stocks.shape[0]
for i in range(stocks.shape[0]):
    stocks.loc[i, 'Number of Shares to Buy'] = math.floor(position_size/stocks['Price'][i])

/home/ne0/.local/lib/python3.8/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [7]:
stocks

    Ticker      Price  One-Year Price Return Number of Shares to Buy
0    WEGE3  71.970001               1.255406                   55578
1    PRIO3  56.500000               1.107423                   70796
2    MGLU3  23.719999               1.069357                  168634
3    CSNA3  25.660000               0.949848                  155884
4    VVAR3  17.730000               0.733138                  225606
5    BRAP4  61.209999               0.703116                   65348
6    USIM5  13.970000               0.605747                  286327
7    VALE3  82.269997               0.599339                   48620
8    RENT3  66.800003               0.553832                   59880
9    SUZB3  52.680000               0.394389                   75930
10   HAPV3  15.210000               0.362903                  262984
11   GOAU4  10.630000               0.345570                  376293
12   NTCO3  49.400002               0.343852                   80971
13   GGBR4  23.049999               0.341676                  173535
14  KLBN11  24.180000               0.337389                  165425
15   MRFG3  14.180000               0.304508                  282087
16   GNDI3  74.389999               0.266428                   53770
17   BTOW3  76.199997               0.254734                   52493
18   B3SA3  58.529999               0.228332                   68341
19   RADL3  24.700001               0.201479                  161943
20   CSAN3  75.570000               0.147434                   52931
21  TAEE11  32.759998               0.118852                  122100
22  BPAC11  82.080002               0.069586                   48732
23   MRVE3  20.030001               0.029291                  199700
24   UGPA3  21.950001               0.026661                  182232